/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // M3 Light scheme
        primary: '#495D92',
        'on-primary': '#FFFFFF',
        'primary-container': '#DAE2FF',
        'on-primary-container': '#314578',
        secondary: '#585E71',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#DDE2F9',
        'on-secondary-container': '#404659',
        tertiary: '#735471',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#FED6F9',
        'on-tertiary-container': '#5A3D59',
        error: '#BA1A1A',
        'on-error': '#FFFFFF',
        'error-container': '#FFDAD6',
        'on-error-container': '#93000A',
        background: '#FAF8FF',
        'on-background': '#1A1B21',
        surface: '#FAF8FF',
        'on-surface': '#1A1B21',
        'surface-variant': '#E1E2EC',
        'on-surface-variant': '#45464F',
        outline: '#757780',
        'outline-variant': '#C5C6D0',
        'inverse-surface': '#2F3036',
        'inverse-on-surface': '#F1F0F7',
        'inverse-primary': '#B2C5FF',
        'surface-dim': '#DAD9E0',
        'surface-bright': '#FAF8FF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F4F3FA',
        'surface-container': '#EEEDF4',
        'surface-container-high': '#E8E7EF',
        'surface-container-highest': '#E3E2E9',
        // Palette shades for hero/accents
        'primary-10': '#001848',
        'primary-20': '#0C2C6C',
        'primary-30': '#294484',
        'primary-40': '#435C9E',
        'primary-80': '#B2C5FF',
        'primary-90': '#DAE2FF',
        'primary-95': '#EEF0FF',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'elevation-1': '0px 1px 2px rgba(0,0,0,0.3), 0px 1px 3px 1px rgba(0,0,0,0.15)',
        'elevation-2': '0px 1px 2px rgba(0,0,0,0.3), 0px 2px 6px 2px rgba(0,0,0,0.15)',
        'elevation-3': '0px 4px 8px 3px rgba(0,0,0,0.15), 0px 1px 3px rgba(0,0,0,0.3)',
        'elevation-4': '0px 6px 10px 4px rgba(0,0,0,0.15), 0px 2px 3px rgba(0,0,0,0.3)',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out',
        'slide-up': 'slideUp 0.6s ease-out',
        'slide-down': 'slideDown 0.2s ease-out',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { '0%': { opacity: '0', transform: 'translateY(-8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
      },
    },
  },
  plugins: [],
};
